name: Deploy Cloudflare Tunnel

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb
          # 先登录，再启动隧道
          cloudflared tunnel login --force
          cloudflared tunnel run "My proxy"
        shell: bash
        timeout-minutes: 0
