name: Deploy Cloudflare Tunnel

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker
        run: |
          docker build -t cloudflared-tunnel .
          docker run -d --restart always cloudflared-tunnel
        shell: bash
        timeout-minutes: 0
